#coding=utf-8
ALL_DATA_KEYS={
    u'TQ_COMP_INDUSTRY': {u'INDCLASSCODE': u'TQ_COMP_INDUSTRY.INDCLASSCODE',
                       u'INDCLASSNAME': u'TQ_COMP_INDUSTRY.INDCLASSNAME',
                       u'LEVEL1CODE': u'TQ_COMP_INDUSTRY.LEVEL1CODE',
                       u'LEVEL1NAME': u'TQ_COMP_INDUSTRY.LEVEL1NAME'},
 u'TQ_QT_SKDAILYPRICE': {u'AVGVOL': u'TQ_QT_SKDAILYPRICE.AVGVOL',
                         u'NEGOTIABLEMV': u'TQ_QT_SKDAILYPRICE.NEGOTIABLEMV',
                         u'TOTMKTCAP': u'TQ_QT_SKDAILYPRICE.TOTMKTCAP'},
 u'TQ_SK_PRORIGHTS': {u'CASHDVARRBEGDATE': u'TQ_SK_PRORIGHTS.CASHDVARRBEGDATE',
                      u'CASHDVARRENDDATE': u'TQ_SK_PRORIGHTS.CASHDVARRENDDATE',
                      u'CUR': u'TQ_SK_PRORIGHTS.CUR',
                      u'GRAOBJTYPE': u'TQ_SK_PRORIGHTS.GRAOBJTYPE',
                      u'PRETAXCASHMAXDVCNY': u'TQ_SK_PRORIGHTS.PRETAXCASHMAXDVCNY',
                      u'PROBONUSRT': u'TQ_SK_PRORIGHTS.PROBONUSRT',
                      u'PROJECTTYPE': u'TQ_SK_PRORIGHTS.PROJECTTYPE',
                      u'SHARRDATE': u'TQ_SK_PRORIGHTS.SHARRDATE',
                      u'TRANADDRT': u'TQ_SK_PRORIGHTS.TRANADDRT',
                      u'XDRDATE': u'TQ_SK_PRORIGHTS.XDRDATE'},
 u'TQ_SK_SHAREHOLDERNUM': {u'ASKAVGSH': u'TQ_SK_SHAREHOLDERNUM.ASKAVGSH',
                           u'TOTALSHAMT': u'TQ_SK_SHAREHOLDERNUM.TOTALSHAMT'},
 u'TQ_SK_SHARESTRUCHG': {u'TOTALSHARE': u'TQ_SK_SHARESTRUCHG.TOTALSHARE'},
 u'TQ_SK_YIELDINDIC': {u'BETA52W': u'TQ_SK_YIELDINDIC.BETA52W'},
 u'adjustfactor': {u'prefactor': u'adjustfactor.prefactor',
                   u'suffactor': u'adjustfactor.suffactor'},
 u'backtest_stock': {u'dn': u'backtest_stock.dn',
                     u'preclose': u'backtest_stock.preclose',
                     u'prehigh': u'backtest_stock.prehigh',
                     u'prelow': u'backtest_stock.prelow',
                     u'preopen': u'backtest_stock.preopen',
                     u'sufclose': u'backtest_stock.sufclose',
                     u'sufhigh': u'backtest_stock.sufhigh',
                     u'suflow': u'backtest_stock.suflow',
                     u'sufopen': u'backtest_stock.sufopen',
                     u'suspension': u'backtest_stock.suspension',
                     u'up': u'backtest_stock.up'},
 u'basic': {u'stock': u'basic.stock'},
 u'check': {u'list': u'check.list',
            u'quit': u'check.quit',
            u'st': u'check.st',
            u'suspension': u'check.suspension'},
 u'equ_factor_AF': {u'DAREC': u'equ_factor_AF.DAREC',
                    u'DAREV': u'equ_factor_AF.DAREV',
                    u'DASREV': u'equ_factor_AF.DASREV',
                    u'FEARNG': u'equ_factor_AF.FEARNG',
                    u'FSALESG': u'equ_factor_AF.FSALESG',
                    u'FY12P': u'equ_factor_AF.FY12P',
                    u'GREC': u'equ_factor_AF.GREC',
                    u'GREV': u'equ_factor_AF.GREV',
                    u'GSREV': u'equ_factor_AF.GSREV',
                    u'REC': u'equ_factor_AF.REC',
                    u'SFY12P': u'equ_factor_AF.SFY12P',
                    u'TRADE_DATE': u'equ_factor_AF.TRADE_DATE'},
 u'equ_factor_CF': {u'ACCA': u'equ_factor_CF.ACCA',
                    u'CFO2EV': u'equ_factor_CF.CFO2EV',
                    u'CTOP': u'equ_factor_CF.CTOP',
                    u'CTP5': u'equ_factor_CF.CTP5',
                    u'CashRateOfSales': u'equ_factor_CF.CashRateOfSales',
                    u'CashToCurrentLiability': u'equ_factor_CF.CashToCurrentLiability',
                    u'FinancingCashGrowRate': u'equ_factor_CF.FinancingCashGrowRate',
                    u'InvestCashGrowRate': u'equ_factor_CF.InvestCashGrowRate',
                    u'NOCFToOperatingNI': u'equ_factor_CF.NOCFToOperatingNI',
                    u'NetProfitCashCover': u'equ_factor_CF.NetProfitCashCover',
                    u'OperCashGrowRate': u'equ_factor_CF.OperCashGrowRate',
                    u'OperCashInToAsset': u'equ_factor_CF.OperCashInToAsset',
                    u'OperCashInToCurrentLiability': u'equ_factor_CF.OperCashInToCurrentLiability',
                    u'SaleServiceCashToOR': u'equ_factor_CF.SaleServiceCashToOR',
                    u'TRADE_DATE': u'equ_factor_CF.TRADE_DATE'},
 u'equ_factor_Growth': {u'DEGM': u'equ_factor_Growth.DEGM',
                        u'EARNMOM': u'equ_factor_Growth.EARNMOM',
                        u'NPParentCompanyGrowRate': u'equ_factor_Growth.NPParentCompanyGrowRate',
                        u'NetAssetGrowRate': u'equ_factor_Growth.NetAssetGrowRate',
                        u'NetCashFlowGrowRate': u'equ_factor_Growth.NetCashFlowGrowRate',
                        u'NetProfitGrowRate': u'equ_factor_Growth.NetProfitGrowRate',
                        u'NetProfitGrowRate3Y': u'equ_factor_Growth.NetProfitGrowRate3Y',
                        u'NetProfitGrowRate5Y': u'equ_factor_Growth.NetProfitGrowRate5Y',
                        u'OperatingProfitGrowRate': u'equ_factor_Growth.OperatingProfitGrowRate',
                        u'OperatingRevenueGrowRate': u'equ_factor_Growth.OperatingRevenueGrowRate',
                        u'OperatingRevenueGrowRate3Y': u'equ_factor_Growth.OperatingRevenueGrowRate3Y',
                        u'OperatingRevenueGrowRate5Y': u'equ_factor_Growth.OperatingRevenueGrowRate5Y',
                        u'TRADE_DATE': u'equ_factor_Growth.TRADE_DATE',
                        u'TotalAssetGrowRate': u'equ_factor_Growth.TotalAssetGrowRate',
                        u'TotalProfitGrowRate': u'equ_factor_Growth.TotalProfitGrowRate'},
 u'equ_factor_MA': {u'ACD20': u'equ_factor_MA.ACD20',
                    u'ACD6': u'equ_factor_MA.ACD6',
                    u'APBMA': u'equ_factor_MA.APBMA',
                    u'BBI': u'equ_factor_MA.BBI',
                    u'BBIC': u'equ_factor_MA.BBIC',
                    u'EMA10': u'equ_factor_MA.EMA10',
                    u'EMA12': u'equ_factor_MA.EMA12',
                    u'EMA120': u'equ_factor_MA.EMA120',
                    u'EMA20': u'equ_factor_MA.EMA20',
                    u'EMA26': u'equ_factor_MA.EMA26',
                    u'EMA5': u'equ_factor_MA.EMA5',
                    u'EMA60': u'equ_factor_MA.EMA60',
                    u'MA10': u'equ_factor_MA.MA10',
                    u'MA10Close': u'equ_factor_MA.MA10Close',
                    u'MA120': u'equ_factor_MA.MA120',
                    u'MA20': u'equ_factor_MA.MA20',
                    u'MA5': u'equ_factor_MA.MA5',
                    u'MA60': u'equ_factor_MA.MA60',
                    u'TEMA10': u'equ_factor_MA.TEMA10',
                    u'TEMA5': u'equ_factor_MA.TEMA5',
                    u'TRADE_DATE': u'equ_factor_MA.TRADE_DATE'},
 u'equ_factor_OBOS': {u'ADTM': u'equ_factor_OBOS.ADTM',
                      u'ARC': u'equ_factor_OBOS.ARC',
                      u'ATR14': u'equ_factor_OBOS.ATR14',
                      u'ATR6': u'equ_factor_OBOS.ATR6',
                      u'BIAS10': u'equ_factor_OBOS.BIAS10',
                      u'BIAS20': u'equ_factor_OBOS.BIAS20',
                      u'BIAS5': u'equ_factor_OBOS.BIAS5',
                      u'BIAS60': u'equ_factor_OBOS.BIAS60',
                      u'BackwardADJ': u'equ_factor_OBOS.BackwardADJ',
                      u'BollDown': u'equ_factor_OBOS.BollDown',
                      u'BollUp': u'equ_factor_OBOS.BollUp',
                      u'CCI10': u'equ_factor_OBOS.CCI10',
                      u'CCI20': u'equ_factor_OBOS.CCI20',
                      u'CCI5': u'equ_factor_OBOS.CCI5',
                      u'CCI88': u'equ_factor_OBOS.CCI88',
                      u'CMO': u'equ_factor_OBOS.CMO',
                      u'CMRA': u'equ_factor_OBOS.CMRA',
                      u'ChandeSD': u'equ_factor_OBOS.ChandeSD',
                      u'ChandeSU': u'equ_factor_OBOS.ChandeSU',
                      u'DBCD': u'equ_factor_OBOS.DBCD',
                      u'DDNBT': u'equ_factor_OBOS.DDNBT',
                      u'DDNCR': u'equ_factor_OBOS.DDNCR',
                      u'DDNSR': u'equ_factor_OBOS.DDNSR',
                      u'DVRAT': u'equ_factor_OBOS.DVRAT',
                      u'DownRVI': u'equ_factor_OBOS.DownRVI',
                      u'FiftyTwoWeekHigh': u'equ_factor_OBOS.FiftyTwoWeekHigh',
                      u'HBETA': u'equ_factor_OBOS.HBETA',
                      u'HSIGMA': u'equ_factor_OBOS.HSIGMA',
                      u'ILLIQUIDITY': u'equ_factor_OBOS.ILLIQUIDITY',
                      u'KDJ_D': u'equ_factor_OBOS.KDJ_D',
                      u'KDJ_J': u'equ_factor_OBOS.KDJ_J',
                      u'KDJ_K': u'equ_factor_OBOS.KDJ_K',
                      u'MAWVAD': u'equ_factor_OBOS.MAWVAD',
                      u'MFI': u'equ_factor_OBOS.MFI',
                      u'Price1M': u'equ_factor_OBOS.Price1M',
                      u'Price1Y': u'equ_factor_OBOS.Price1Y',
                      u'Price3M': u'equ_factor_OBOS.Price3M',
                      u'REVS10': u'equ_factor_OBOS.REVS10',
                      u'REVS120': u'equ_factor_OBOS.REVS120',
                      u'REVS20': u'equ_factor_OBOS.REVS20',
                      u'REVS20Indu1': u'equ_factor_OBOS.REVS20Indu1',
                      u'REVS250': u'equ_factor_OBOS.REVS250',
                      u'REVS5': u'equ_factor_OBOS.REVS5',
                      u'REVS5Indu1': u'equ_factor_OBOS.REVS5Indu1',
                      u'REVS5m20': u'equ_factor_OBOS.REVS5m20',
                      u'REVS5m60': u'equ_factor_OBOS.REVS5m60',
                      u'REVS60': u'equ_factor_OBOS.REVS60',
                      u'REVS750': u'equ_factor_OBOS.REVS750',
                      u'ROC20': u'equ_factor_OBOS.ROC20',
                      u'ROC6': u'equ_factor_OBOS.ROC6',
                      u'RSI': u'equ_factor_OBOS.RSI',
                      u'RVI': u'equ_factor_OBOS.RVI',
                      u'Rank1M': u'equ_factor_OBOS.Rank1M',
                      u'SBM': u'equ_factor_OBOS.SBM',
                      u'SRMI': u'equ_factor_OBOS.SRMI',
                      u'STM': u'equ_factor_OBOS.STM',
                      u'Skewness': u'equ_factor_OBOS.Skewness',
                      u'TRADE_DATE': u'equ_factor_OBOS.TRADE_DATE',
                      u'UpRVI': u'equ_factor_OBOS.UpRVI',
                      u'Volatility': u'equ_factor_OBOS.Volatility',
                      u'Volumn1M': u'equ_factor_OBOS.Volumn1M',
                      u'Volumn3M': u'equ_factor_OBOS.Volumn3M',
                      u'WVAD': u'equ_factor_OBOS.WVAD'},
 u'equ_factor_OC': {u'ARTDays': u'equ_factor_OC.ARTDays',
                    u'ARTRate': u'equ_factor_OC.ARTRate',
                    u'AccountsPayablesTDays': u'equ_factor_OC.AccountsPayablesTDays',
                    u'AccountsPayablesTRate': u'equ_factor_OC.AccountsPayablesTRate',
                    u'CashConversionCycle': u'equ_factor_OC.CashConversionCycle',
                    u'CurrentAssetsTRate': u'equ_factor_OC.CurrentAssetsTRate',
                    u'EquityTRate': u'equ_factor_OC.EquityTRate',
                    u'FixedAssetsTRate': u'equ_factor_OC.FixedAssetsTRate',
                    u'InventoryTDays': u'equ_factor_OC.InventoryTDays',
                    u'InventoryTRate': u'equ_factor_OC.InventoryTRate',
                    u'OperatingCycle': u'equ_factor_OC.OperatingCycle',
                    u'TRADE_DATE': u'equ_factor_OC.TRADE_DATE',
                    u'TotalAssetsTRate': u'equ_factor_OC.TotalAssetsTRate'},
 u'equ_factor_PQ': {u'AdminiExpenseRate': u'equ_factor_PQ.AdminiExpenseRate',
                    u'EBITToTOR': u'equ_factor_PQ.EBITToTOR',
                    u'EGRO': u'equ_factor_PQ.EGRO',
                    u'ETOP': u'equ_factor_PQ.ETOP',
                    u'ETP5': u'equ_factor_PQ.ETP5',
                    u'FinancialExpenseRate': u'equ_factor_PQ.FinancialExpenseRate',
                    u'GrossIncomeRatio': u'equ_factor_PQ.GrossIncomeRatio',
                    u'NPToTOR': u'equ_factor_PQ.NPToTOR',
                    u'NetNonOIToTP': u'equ_factor_PQ.NetNonOIToTP',
                    u'NetNonOIToTPLatest': u'equ_factor_PQ.NetNonOIToTPLatest',
                    u'NetProfitRatio': u'equ_factor_PQ.NetProfitRatio',
                    u'OperatingExpenseRate': u'equ_factor_PQ.OperatingExpenseRate',
                    u'OperatingProfitRatio': u'equ_factor_PQ.OperatingProfitRatio',
                    u'OperatingProfitToTOR': u'equ_factor_PQ.OperatingProfitToTOR',
                    u'PeriodCostsRate': u'equ_factor_PQ.PeriodCostsRate',
                    u'ROA': u'equ_factor_PQ.ROA',
                    u'ROA5': u'equ_factor_PQ.ROA5',
                    u'ROE': u'equ_factor_PQ.ROE',
                    u'ROE5': u'equ_factor_PQ.ROE5',
                    u'SUE': u'equ_factor_PQ.SUE',
                    u'SUOI': u'equ_factor_PQ.SUOI',
                    u'SalesCostRatio': u'equ_factor_PQ.SalesCostRatio',
                    u'TRADE_DATE': u'equ_factor_PQ.TRADE_DATE',
                    u'TaxRatio': u'equ_factor_PQ.TaxRatio',
                    u'TotalProfitCostRatio': u'equ_factor_PQ.TotalProfitCostRatio'},
 u'equ_factor_PSI': {u'CapitalSurplusFundPS': u'equ_factor_PSI.CapitalSurplusFundPS',
                     u'CashDividendCover': u'equ_factor_PSI.CashDividendCover',
                     u'CashEquivalentPS': u'equ_factor_PSI.CashEquivalentPS',
                     u'CashFlowPS': u'equ_factor_PSI.CashFlowPS',
                     u'DilutedEPS': u'equ_factor_PSI.DilutedEPS',
                     u'DividendCover': u'equ_factor_PSI.DividendCover',
                     u'DividendPS': u'equ_factor_PSI.DividendPS',
                     u'DividendPaidRatio': u'equ_factor_PSI.DividendPaidRatio',
                     u'EPS': u'equ_factor_PSI.EPS',
                     u'EPSTTM': u'equ_factor_PSI.EPSTTM',
                     u'NetAssetPS': u'equ_factor_PSI.NetAssetPS',
                     u'OperCashFlowPS': u'equ_factor_PSI.OperCashFlowPS',
                     u'OperatingProfitPS': u'equ_factor_PSI.OperatingProfitPS',
                     u'OperatingProfitPSLatest': u'equ_factor_PSI.OperatingProfitPSLatest',
                     u'OperatingRevenuePS': u'equ_factor_PSI.OperatingRevenuePS',
                     u'OperatingRevenuePSLatest': u'equ_factor_PSI.OperatingRevenuePSLatest',
                     u'RetainedEarningRatio': u'equ_factor_PSI.RetainedEarningRatio',
                     u'RetainedEarningsPS': u'equ_factor_PSI.RetainedEarningsPS',
                     u'SurplusReserveFundPS': u'equ_factor_PSI.SurplusReserveFundPS',
                     u'TORPS': u'equ_factor_PSI.TORPS',
                     u'TORPSLatest': u'equ_factor_PSI.TORPSLatest',
                     u'TRADE_DATE': u'equ_factor_PSI.TRADE_DATE',
                     u'UndividedProfitPS': u'equ_factor_PSI.UndividedProfitPS'},
 u'equ_factor_Power': {u'AR': u'equ_factor_Power.AR',
                       u'ARBR': u'equ_factor_Power.ARBR',
                       u'BR': u'equ_factor_Power.BR',
                       u'BearPower': u'equ_factor_Power.BearPower',
                       u'BullPower': u'equ_factor_Power.BullPower',
                       u'CR20': u'equ_factor_Power.CR20',
                       u'Elder': u'equ_factor_Power.Elder',
                       u'JDQS20': u'equ_factor_Power.JDQS20',
                       u'MassIndex': u'equ_factor_Power.MassIndex',
                       u'NVI': u'equ_factor_Power.NVI',
                       u'PSY': u'equ_factor_Power.PSY',
                       u'PVI': u'equ_factor_Power.PVI',
                       u'RC12': u'equ_factor_Power.RC12',
                       u'RC24': u'equ_factor_Power.RC24',
                       u'RSTR12': u'equ_factor_Power.RSTR12',
                       u'RSTR24': u'equ_factor_Power.RSTR24',
                       u'TOBT': u'equ_factor_Power.TOBT',
                       u'TRADE_DATE': u'equ_factor_Power.TRADE_DATE'},
 u'equ_factor_SC': {u'BLEV': u'equ_factor_SC.BLEV',
                    u'BondsPayableToAsset': u'equ_factor_SC.BondsPayableToAsset',
                    u'CurrentAssetsRatio': u'equ_factor_SC.CurrentAssetsRatio',
                    u'CurrentRatio': u'equ_factor_SC.CurrentRatio',
                    u'DebtEquityRatio': u'equ_factor_SC.DebtEquityRatio',
                    u'DebtsAssetRatio': u'equ_factor_SC.DebtsAssetRatio',
                    u'EquityFixedAssetRatio': u'equ_factor_SC.EquityFixedAssetRatio',
                    u'EquityToAsset': u'equ_factor_SC.EquityToAsset',
                    u'FixAssetRatio': u'equ_factor_SC.FixAssetRatio',
                    u'IntangibleAssetRatio': u'equ_factor_SC.IntangibleAssetRatio',
                    u'InterestCover': u'equ_factor_SC.InterestCover',
                    u'LongDebtToAsset': u'equ_factor_SC.LongDebtToAsset',
                    u'LongDebtToWorkingCapital': u'equ_factor_SC.LongDebtToWorkingCapital',
                    u'LongTermDebtToAsset': u'equ_factor_SC.LongTermDebtToAsset',
                    u'MLEV': u'equ_factor_SC.MLEV',
                    u'NonCurrentAssetsRatio': u'equ_factor_SC.NonCurrentAssetsRatio',
                    u'QuickRatio': u'equ_factor_SC.QuickRatio',
                    u'TRADE_DATE': u'equ_factor_SC.TRADE_DATE'},
 u'equ_factor_Trend': {u'AD': u'equ_factor_Trend.AD',
                       u'AD20': u'equ_factor_Trend.AD20',
                       u'AD6': u'equ_factor_Trend.AD6',
                       u'ADX': u'equ_factor_Trend.ADX',
                       u'ADXR': u'equ_factor_Trend.ADXR',
                       u'ASI': u'equ_factor_Trend.ASI',
                       u'Aroon': u'equ_factor_Trend.Aroon',
                       u'AroonDown': u'equ_factor_Trend.AroonDown',
                       u'AroonUp': u'equ_factor_Trend.AroonUp',
                       u'ChaikinOscillator': u'equ_factor_Trend.ChaikinOscillator',
                       u'ChaikinVolatility': u'equ_factor_Trend.ChaikinVolatility',
                       u'CoppockCurve': u'equ_factor_Trend.CoppockCurve',
                       u'DDI': u'equ_factor_Trend.DDI',
                       u'DEA': u'equ_factor_Trend.DEA',
                       u'DHILO': u'equ_factor_Trend.DHILO',
                       u'DIF': u'equ_factor_Trend.DIF',
                       u'DIFF': u'equ_factor_Trend.DIFF',
                       u'DIZ': u'equ_factor_Trend.DIZ',
                       u'EMV14': u'equ_factor_Trend.EMV14',
                       u'EMV6': u'equ_factor_Trend.EMV6',
                       u'Hurst': u'equ_factor_Trend.Hurst',
                       u'MA10RegressCoeff12': u'equ_factor_Trend.MA10RegressCoeff12',
                       u'MA10RegressCoeff6': u'equ_factor_Trend.MA10RegressCoeff6',
                       u'MACD': u'equ_factor_Trend.MACD',
                       u'MTM': u'equ_factor_Trend.MTM',
                       u'MTMMA': u'equ_factor_Trend.MTMMA',
                       u'PLRC12': u'equ_factor_Trend.PLRC12',
                       u'PLRC6': u'equ_factor_Trend.PLRC6',
                       u'PVT': u'equ_factor_Trend.PVT',
                       u'PVT12': u'equ_factor_Trend.PVT12',
                       u'PVT6': u'equ_factor_Trend.PVT6',
                       u'SwingIndex': u'equ_factor_Trend.SwingIndex',
                       u'TRADE_DATE': u'equ_factor_Trend.TRADE_DATE',
                       u'TRIX10': u'equ_factor_Trend.TRIX10',
                       u'TRIX5': u'equ_factor_Trend.TRIX5',
                       u'UOS': u'equ_factor_Trend.UOS',
                       u'Ulcer10': u'equ_factor_Trend.Ulcer10',
                       u'Ulcer5': u'equ_factor_Trend.Ulcer5',
                       u'minusDI': u'equ_factor_Trend.minusDI',
                       u'plusDI': u'equ_factor_Trend.plusDI'},
 u'equ_factor_VS': {u'ASSI': u'equ_factor_VS.ASSI',
                    u'ForwardPE': u'equ_factor_VS.ForwardPE',
                    u'LCAP': u'equ_factor_VS.LCAP',
                    u'LFLO': u'equ_factor_VS.LFLO',
                    u'PB': u'equ_factor_VS.PB',
                    u'PBIndu': u'equ_factor_VS.PBIndu',
                    u'PCF': u'equ_factor_VS.PCF',
                    u'PCFIndu': u'equ_factor_VS.PCFIndu',
                    u'PE': u'equ_factor_VS.PE',
                    u'PEG3Y': u'equ_factor_VS.PEG3Y',
                    u'PEG5Y': u'equ_factor_VS.PEG5Y',
                    u'PEHist120': u'equ_factor_VS.PEHist120',
                    u'PEHist20': u'equ_factor_VS.PEHist20',
                    u'PEHist250': u'equ_factor_VS.PEHist250',
                    u'PEHist60': u'equ_factor_VS.PEHist60',
                    u'PEIndu': u'equ_factor_VS.PEIndu',
                    u'PS': u'equ_factor_VS.PS',
                    u'PSIndu': u'equ_factor_VS.PSIndu',
                    u'StaticPE': u'equ_factor_VS.StaticPE',
                    u'TA2EV': u'equ_factor_VS.TA2EV',
                    u'TRADE_DATE': u'equ_factor_VS.TRADE_DATE'},
 u'equ_factor_Volume': {u'DAVOL10': u'equ_factor_Volume.DAVOL10',
                        u'DAVOL20': u'equ_factor_Volume.DAVOL20',
                        u'DAVOL5': u'equ_factor_Volume.DAVOL5',
                        u'KlingerOscillator': u'equ_factor_Volume.KlingerOscillator',
                        u'MoneyFlow20': u'equ_factor_Volume.MoneyFlow20',
                        u'OBV': u'equ_factor_Volume.OBV',
                        u'OBV20': u'equ_factor_Volume.OBV20',
                        u'OBV6': u'equ_factor_Volume.OBV6',
                        u'TRADE_DATE': u'equ_factor_Volume.TRADE_DATE',
                        u'TVMA20': u'equ_factor_Volume.TVMA20',
                        u'TVMA6': u'equ_factor_Volume.TVMA6',
                        u'TVSTD20': u'equ_factor_Volume.TVSTD20',
                        u'TVSTD6': u'equ_factor_Volume.TVSTD6',
                        u'VDEA': u'equ_factor_Volume.VDEA',
                        u'VDIFF': u'equ_factor_Volume.VDIFF',
                        u'VEMA10': u'equ_factor_Volume.VEMA10',
                        u'VEMA12': u'equ_factor_Volume.VEMA12',
                        u'VEMA26': u'equ_factor_Volume.VEMA26',
                        u'VEMA5': u'equ_factor_Volume.VEMA5',
                        u'VMACD': u'equ_factor_Volume.VMACD',
                        u'VOL10': u'equ_factor_Volume.VOL10',
                        u'VOL120': u'equ_factor_Volume.VOL120',
                        u'VOL20': u'equ_factor_Volume.VOL20',
                        u'VOL240': u'equ_factor_Volume.VOL240',
                        u'VOL5': u'equ_factor_Volume.VOL5',
                        u'VOL60': u'equ_factor_Volume.VOL60',
                        u'VOSC': u'equ_factor_Volume.VOSC',
                        u'VR': u'equ_factor_Volume.VR',
                        u'VROC12': u'equ_factor_Volume.VROC12',
                        u'VROC6': u'equ_factor_Volume.VROC6',
                        u'VSTD10': u'equ_factor_Volume.VSTD10',
                        u'VSTD20': u'equ_factor_Volume.VSTD20'},
 u'exchange_date': {u'in_trade': u'exchange_date.in_trade'},
 u'factor': {u'class': u'factor.class',
             u'name': u'factor.name',
             u'score_order': u'factor.score_order',
             u'type': u'factor.type'},
 u'rating': {u'symbol': {u'chip': {u'askavgsh-1': u'rating.symbol.chip.askavgsh-1',#每日每户持股数动量
                                   u'askavgsh-120': u'rating.symbol.chip.askavgsh-120',#6个月平均每户持股数动量
                                   u'askavgsh-60': u'rating.symbol.chip.askavgsh-60',#3个月平均每户持股数动量
                                   u'avgvol-1': u'rating.symbol.chip.avgvol-1',#每日平均每笔成交量动量
                                   u'avgvol-120': u'rating.symbol.chip.avgvol-120',#6个月平均每笔成交量动量
                                   u'avgvol-60': u'rating.symbol.chip.avgvol-60',#3个月平均每笔成交量动量
                                   u'totalshamt-1': u'rating.symbol.chip.totalshamt-1',#每日平均股东总户数动量
                                   u'totalshamt-120': u'rating.symbol.chip.totalshamt-120',#6个月平均股东总户数动量
                                   u'totalshamt-60': u'rating.symbol.chip.totalshamt-60',#3个月平均股东总户数动量
                                   u'turn_rate-1': u'rating.symbol.chip.turn_rate-1',#1日换手率动量
                                   u'turn_rate-120': u'rating.symbol.chip.turn_rate-120',#6个月平均换手率动量
                                   u'turn_rate-60': u'rating.symbol.chip.turn_rate-60',#3个月平均换手率动量
                                   u'volume-1': u'rating.symbol.chip.volume-1',#1天成交量动量
                                   u'volume-120': u'rating.symbol.chip.volume-120',#6个月平均成交量动量
                                   u'volume-60': u'rating.symbol.chip.volume-60'},  #3个月平均成交量
                         u'filter': {u'filter20_5': u'rating.symbol.filter.filter20_5',#停牌后过滤
                                     u'new20': u'rating.symbol.filter.new20'},  #新股过滤
                         u'growth': {u'main_busi_grow_rate': u'rating.symbol.growth.main_busi_grow_rate',#主营业务收入增长率
                                     u'netass_grow_rate': u'rating.symbol.growth.netass_grow_rate',#净资产增长率
                                     u'netinc_grow_rate': u'rating.symbol.growth.netinc_grow_rate'},  #净利润增长率
                         u'momentum': {u'win120': u'rating.symbol.momentum.win120',#6个月涨跌幅
                                       u'win20': u'rating.symbol.momentum.win20',#1个月涨跌幅
                                       u'win240': u'rating.symbol.momentum.win240',#12个月涨跌幅
                                       u'win5': u'rating.symbol.momentum.win5',#1周涨跌幅
                                       u'win60': u'rating.symbol.momentum.win60'},  #3个月涨跌幅
                         u'other': {u'beta52w': u'rating.symbol.other.beta52w',#52周beta
                                    u'high_send': u'rating.symbol.other.high_send',#高送配（填充）
                                    u'high_send_no_value': u'rating.symbol.other.high_send_no_value',#高送配（不填充）
                                    u'pre_dv': u'rating.symbol.other.pre_dv',#分红（填充）
                                    u'pre_dv_no_value': u'rating.symbol.other.pre_dv_no_value',#分红（不填充）
                                    u'tclose': u'rating.symbol.other.tclose'},  #收盘价
                         u'quality': {u'assliab_rate': u'rating.symbol.quality.assliab_rate',#资产负债率
                                      u'dilutedroe': u'rating.symbol.quality.dilutedroe',#净资产收益率
                                      u'invturn_rate': u'rating.symbol.quality.invturn_rate',#存货周转率
                                      u'sale_gross_profit_rto': u'rating.symbol.quality.sale_gross_profit_rto'},  #销售毛利率
                         u'scale': {u'negotiablemv': u'rating.symbol.scale.negotiablemv',#流通市值
                                    u'negotiablemv_totmktcap': u'rating.symbol.scale.negotiablemv_totmktcap',#流通市值和总市值的比率
                                    u'totalshare': u'rating.symbol.scale.totalshare',#总股本
                                    u'totmktcap': u'rating.symbol.scale.totmktcap'},  #总市值
                         u'scale_log': {u'negotiablemv': u'rating.symbol.scale_log.negotiablemv',  # 流通市值
                                    u'totalshare': u'rating.symbol.scale_log.totalshare',  # 总股本
                                    u'totmktcap': u'rating.symbol.scale_log.totmktcap'},  # 总市值
                         u'value': {u'dy': u'rating.symbol.value.dy',#股息率
                                    u'evebitda': u'rating.symbol.value.evebitda',#企业价值/税息折旧摊销前利润
                                    u'pb': u'rating.symbol.value.pb',#市净率
                                    u'pcttm': u'rating.symbol.value.pcttm',#市现率
                                    u'pettm': u'rating.symbol.value.pettm',#市盈率
                                    u'psttm': u'rating.symbol.value.psttm'}}},#市销率
 u'stock': {u'compcode': u'stock.compcode',
            u'delist_date': u'stock.delist_date',
            u'exchange': u'stock.exchange',
            u'isvalid': u'stock.isvalid',
            u'list_date': u'stock.list_date',
            u'se_name': u'stock.se_name',
            u'setype': u'stock.setype',
            u'symbol': u'stock.symbol'},
 u'stock_adjust_price': {u'close_price': u'stock_adjust_price.close_price',
                         u'suf_close_price': u'stock_adjust_price.suf_close_price',
                         u'suf_high_price': u'stock_adjust_price.suf_high_price',
                         u'suf_low_price': u'stock_adjust_price.suf_low_price',
                         u'suf_open_price': u'stock_adjust_price.suf_open_price'},
 u'stock_delisting_risk_announcemt': {u'risk_release_date': u'stock_delisting_risk_announcemt.risk_release_date'},
 u'stock_ix_value': {u'amount': u'stock_ix_value.amount',
                     u'close': u'stock_ix_value.close',
                     u'exchange': u'stock_ix_value.exchange',
                     u'high': u'stock_ix_value.high',
                     u'last_close': u'stock_ix_value.last_close',
                     u'low': u'stock_ix_value.low',
                     u'open': u'stock_ix_value.open',
                     u'pct_change': u'stock_ix_value.pct_change',
                     u'point_change': u'stock_ix_value.point_change',
                     u'volume': u'stock_ix_value.volume'},
 u'stock_price': {u'close_price': u'stock_price.close_price',
                  u'high_price': u'stock_price.high_price',
                  u'last_close_price': u'stock_price.last_close_price',
                  u'low_price': u'stock_price.low_price',
                  u'open_price': u'stock_price.open_price',
                  u'turn_rate': u'stock_price.turn_rate',
                  u'volume': u'stock_price.volume'},
 u'stock_price_adjust': {u'pre_factor': u'stock_price_adjust.pre_factor',
                         u'suf_factor': u'stock_price_adjust.suf_factor',
                         u'xdy': u'stock_price_adjust.xdy'},
 u'stock_quality_factor': {u'assliab_rate': u'stock_quality_factor.assliab_rate',
                           u'invturn_rate': u'stock_quality_factor.invturn_rate'},
 u'stock_report_factor': {u'dilutedroe': u'stock_report_factor.dilutedroe',
                          u'main_busi_grow_rate': u'stock_report_factor.main_busi_grow_rate',
                          u'netass_grow_rate': u'stock_report_factor.netass_grow_rate',
                          u'netinc_grow_rate': u'stock_report_factor.netinc_grow_rate',
                          u'sale_gross_profit_rto': u'stock_report_factor.sale_gross_profit_rto'},
 u'stock_st_list': {u'out_date': u'stock_st_list.out_date'},
 u'stock_value_factor': {u'dy': u'stock_value_factor.dy',
                         u'evebitda': u'stock_value_factor.evebitda',
                         u'pb': u'stock_value_factor.pb',
                         u'pcttm': u'stock_value_factor.pcttm',
                         u'pettm': u'stock_value_factor.pettm',
                         u'psttm': u'stock_value_factor.psttm'},
 u'technital': {u'2070000060': {u'ATR_21_2dot5': u'technital.2070000060.ATR_21_2.5',#波动率
                                u'BOLL_20_1dot5_1dot5': u'technital.2070000060.BOLL_20_1.5_1.5',#BOLL
                                u'FASTMA_5_20': u'technital.2070000060.FASTMA_5_20',#短均线
                                u'KDJ_21_13_13': u'technital.2070000060.KDJ_21_13_13',#KDJ
                                u'RSI_10_16_85': u'technital.2070000060.RSI_10_16_85',#RSI
                                u'SLOWMA_8_34': u'technital.2070000060.SLOWMA_8_34',#长均线
                                u'TURTLE_55_21': u'technital.2070000060.TURTLE_55_21',#海龟法则
                                u'VOL_55_1dot5': u'technital.2070000060.VOL_55_1.5',#成交量
                                u'DEFAULTBUY_1':u'technital.2070000060.DEFAULTBUY_1'}},#默认全部买入
}